export const GET_POKEDEX_LIST = 'GET_POKEDEX_LIST';
export const SET_POKEDEX_LIST = 'SET_POKEDEX_LIST';
export const GET_SELECTED_POKEMON = 'GET_SELECTED_POKEMON';
export const SET_SELECTED_POKEMON = 'SET_SELECTED_POKEMON';